<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BusinessPartnerController;
use App\Http\Controllers\Api\CashAccountController;
use App\Http\Controllers\Api\CashCountController;
use App\Http\Controllers\Api\CashCustodianHandoverController;
use App\Http\Controllers\Api\CashMovementController;
use App\Http\Controllers\Api\CashTransferController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CollectionsController;
use App\Http\Controllers\Api\CompanyController;
use App\Http\Controllers\Api\CompanyProfileController;
use App\Http\Controllers\Api\CompanySetupController;
use App\Http\Controllers\Api\ExpenseCompletionController;
use App\Http\Controllers\Api\ExpenseController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\MasterRegistryController;
use App\Http\Controllers\Api\OpeningBalanceController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\ProductServiceController;
use App\Http\Controllers\Api\PurchasingController;
use App\Http\Controllers\Api\ReconciliationAdjustmentController;
use App\Http\Controllers\Api\ReconciliationController;
use App\Http\Controllers\Api\ReferenceRegistryController;
use App\Http\Controllers\Api\ReportsController;
use App\Http\Controllers\Api\SalesController;
use App\Http\Controllers\Api\StatementImportController;
use App\Http\Controllers\Api\UnitController;
use App\Http\Controllers\Api\UserAccessController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::get('/health', HealthController::class);
    Route::get('/setup/status', [CompanySetupController::class, 'status']);
    Route::post('/setup/bootstrap', [CompanySetupController::class, 'bootstrap'])->middleware('throttle:auth');
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:auth');
    Route::post('/auth/invitations/accept', [UserAccessController::class, 'accept'])->middleware('throttle:auth');

    Route::middleware('auth:sanctum')->group(function () {
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::middleware('active.user')->group(function () {
            Route::get('/auth/me', [AuthController::class, 'me']);
            Route::get('/companies', [CompanyController::class, 'index']);
            Route::post('/companies/{company}/activate', [CompanyController::class, 'activate']);

            Route::middleware('company.context')->group(function () {
                Route::get('/context/company', [CompanyController::class, 'current']);
                Route::prefix('reports')->group(function () {
                    Route::get('/catalog', [ReportsController::class, 'catalog'])->middleware('permission:reports.view');
                    Route::get('/catalog/{key}', [ReportsController::class, 'definition'])->middleware('permission:reports.catalog.detail');
                    Route::post('/requests', [ReportsController::class, 'generate'])->middleware('permission:reports.generate');
                    Route::get('/requests/{id}/status', [ReportsController::class, 'request'])->middleware('permission:reports.view');
                    Route::get('/requests/{id}', [ReportsController::class, 'request'])->middleware('permission:reports.view');
                    Route::post('/requests/{id}/cancel', [ReportsController::class, 'cancelRequest'])->middleware('permission:reports.requests.cancel');
                    Route::post('/requests/{id}/retry', [ReportsController::class, 'retryRequest'])->middleware('permission:reports.requests.retry');
                    Route::get('/outputs/{id}', [ReportsController::class, 'output'])->middleware('permission:reports.display');
                    Route::get('/outputs/{id}/download', [ReportsController::class, 'download'])->middleware('permission:reports.export');
                    Route::post('/outputs/{id}/print', [ReportsController::class, 'print'])->middleware('permission:reports.print');
                    Route::post('/outputs/{id}/drill-down', [ReportsController::class, 'drillDown'])->middleware('permission:reports.drilldown');
                    Route::post('/outputs/{id}/snapshot', [ReportsController::class, 'snapshot'])->middleware('permission:reports.snapshot.create');
                    Route::get('/history', [ReportsController::class, 'history'])->middleware('permission:reports.history.view');
                    Route::get('/recent', [ReportsController::class, 'history'])->middleware('permission:reports.history.view');
                    Route::get('/favorites', [ReportsController::class, 'favorites'])->middleware('permission:reports.favorite');
                    Route::post('/favorites', [ReportsController::class, 'favorite'])->middleware('permission:reports.favorite');
                    Route::delete('/favorites/{id}', [ReportsController::class, 'removeFavorite'])->middleware('permission:reports.favorite');
                    Route::get('/saved-views', [ReportsController::class, 'savedViews'])->middleware('permission:reports.saved-views');
                    Route::post('/saved-views', [ReportsController::class, 'saveView'])->middleware('permission:reports.saved-views');
                    Route::patch('/saved-views/{id}', [ReportsController::class, 'saveView'])->middleware('permission:reports.saved-views');
                    Route::delete('/saved-views/{id}', [ReportsController::class, 'deleteView'])->middleware('permission:reports.saved-views');
                    Route::get('/schedules', [ReportsController::class, 'schedules'])->middleware('permission:reports.schedules.view');
                    Route::post('/schedules', [ReportsController::class, 'storeSchedule'])->middleware('permission:reports.schedules.manage');
                    Route::patch('/schedules/{id}', [ReportsController::class, 'updateSchedule'])->middleware('permission:reports.schedules.manage');
                    Route::get('/schedules/{id}/occurrences', [ReportsController::class, 'scheduleOccurrences'])->middleware('permission:reports.schedules.view');
                    Route::post('/schedules/{id}/{action}', [ReportsController::class, 'scheduleAction'])->whereIn('action', ['activate', 'resume', 'pause', 'cancel', 'run'])->middleware('permission:reports.schedules.manage');
                    Route::get('/deliveries', [ReportsController::class, 'deliveries'])->middleware('permission:reports.delivery.view');
                    Route::post('/deliveries/{id}/retry', [ReportsController::class, 'retryDelivery'])->middleware('permission:reports.delivery.retry');
                    Route::post('/compare', [ReportsController::class, 'compare'])->middleware('permission:reports.compare');
                    Route::get('/analytics', [ReportsController::class, 'analytics'])->middleware('permission:reports.analytics.view');
                    Route::get('/definitions', [ReportsController::class, 'definitions'])->middleware('permission:reports.definitions.manage');
                    Route::post('/definitions/{key}/supersede', [ReportsController::class, 'supersedeDefinition'])->middleware('permission:reports.definitions.manage');
                    Route::post('/definitions/{id}/publish', [ReportsController::class, 'publishDefinition'])->middleware('permission:reports.definitions.publish');
                    Route::post('/definitions/{id}/deactivate', [ReportsController::class, 'deactivateDefinition'])->middleware('permission:reports.definitions.publish');
                    Route::get('/packs', [ReportsController::class, 'packs'])->middleware('permission:reports.packs.view');
                    Route::post('/packs', [ReportsController::class, 'storePack'])->middleware('permission:reports.packs.manage');
                    Route::post('/packs/{id}/items', [ReportsController::class, 'addPackItem'])->middleware('permission:reports.packs.manage');
                    Route::post('/packs/{id}/{action}', [ReportsController::class, 'packAction'])->whereIn('action', ['generate', 'review', 'publish', 'archive', 'supersede'])->middleware('permission:reports.packs.manage');
                    Route::post('/retention/purge', [ReportsController::class, 'purge'])->middleware('permission:reports.retention.manage');
                });
                Route::prefix('payments')->group(function () {
                    Route::get('/lookups', [PaymentController::class, 'lookups'])->middleware('permission:payments.view');
                    Route::get('/summary', [PaymentController::class, 'summary'])->middleware('permission:payments.view');
                    Route::get('/workbench', [PaymentController::class, 'workbench'])->middleware('permission:payments.workbench.view');
                    Route::get('/requests', [PaymentController::class, 'requests'])->middleware('permission:payments.view');
                    Route::post('/requests', [PaymentController::class, 'storeRequest'])->middleware('permission:payments.requests.create');
                    Route::get('/requests/{id}', [PaymentController::class, 'showRequest'])->middleware('permission:payments.view');
                    Route::post('/requests/{id}/submit', [PaymentController::class, 'requestAction'])->defaults('action', 'submit')->middleware('permission:payments.requests.submit');
                    Route::post('/requests/{id}/return', [PaymentController::class, 'requestAction'])->defaults('action', 'return')->middleware('permission:payments.requests.update');
                    Route::post('/requests/{id}/approve', [PaymentController::class, 'requestAction'])->defaults('action', 'approve')->middleware('permission:payments.approve');
                    Route::post('/requests/{id}/reject', [PaymentController::class, 'requestAction'])->defaults('action', 'reject')->middleware('permission:payments.reject');
                    Route::post('/requests/{id}/cancel', [PaymentController::class, 'requestAction'])->defaults('action', 'cancel')->middleware('permission:payments.requests.update');
                    Route::post('/requests/{id}/convert', [PaymentController::class, 'convert'])->middleware('permission:payments.create');
                    Route::get('/attention', [PaymentController::class, 'attention'])->middleware('permission:payments.view');
                    Route::get('/reports', [PaymentController::class, 'report'])->middleware('permission:payments.reports.view');
                    Route::get('/advances', [PaymentController::class, 'advances'])->middleware('permission:payments.advances.view');
                    Route::post('/advances', [PaymentController::class, 'storeAdvance'])->middleware('permission:payments.advances.create');
                    Route::post('/advances/{id}/apply', [PaymentController::class, 'applyAdvance'])->middleware('permission:payments.allocations.reallocate');
                    Route::get('/checks', [PaymentController::class, 'checks'])->middleware('permission:payments.checks.view');
                    Route::post('/checks/{id}/{action}', [PaymentController::class, 'checkAction'])->middleware('permission:payments.checks.view');
                    Route::get('/batches', [PaymentController::class, 'batches'])->middleware('permission:payments.batches.view');
                    Route::post('/batches', [PaymentController::class, 'storeBatch'])->middleware('permission:payments.batches.create');
                    Route::get('/batches/{id}', [PaymentController::class, 'showBatch'])->middleware('permission:payments.batches.view');
                    Route::post('/batches/{id}/items', [PaymentController::class, 'batchItems'])->middleware('permission:payments.batches.update');
                    Route::post('/batches/{id}/{action}', [PaymentController::class, 'batchAction'])->middleware('permission:payments.batches.update');
                    Route::get('/', [PaymentController::class, 'payments'])->middleware('permission:payments.view');
                    Route::post('/', [PaymentController::class, 'store'])->middleware('permission:payments.create');
                    Route::get('/{id}/timeline', [PaymentController::class, 'timeline'])->middleware('permission:payments.history');
                    Route::post('/{id}/submit', [PaymentController::class, 'action'])->defaults('action', 'submit')->middleware('permission:payments.submit');
                    Route::post('/{id}/return', [PaymentController::class, 'action'])->defaults('action', 'return')->middleware('permission:payments.reject');
                    Route::post('/{id}/approve', [PaymentController::class, 'action'])->defaults('action', 'approve')->middleware('permission:payments.approve');
                    Route::post('/{id}/reject', [PaymentController::class, 'action'])->defaults('action', 'reject')->middleware('permission:payments.reject');
                    Route::post('/{id}/schedule', [PaymentController::class, 'action'])->defaults('action', 'schedule')->middleware('permission:payments.schedule');
                    Route::post('/{id}/release', [PaymentController::class, 'action'])->defaults('action', 'release')->middleware('permission:payments.release');
                    Route::post('/{id}/confirm', [PaymentController::class, 'action'])->defaults('action', 'confirm')->middleware('permission:payments.manual-confirm');
                    Route::post('/{id}/confirm-cash', [PaymentController::class, 'action'])->defaults('action', 'confirm')->middleware('permission:payments.cash.confirm');
                    Route::post('/{id}/confirm-electronic', [PaymentController::class, 'action'])->defaults('action', 'confirm')->middleware('permission:payments.electronic.confirm');
                    Route::post('/{id}/pending', [PaymentController::class, 'action'])->defaults('action', 'pending')->middleware('permission:payments.pending');
                    Route::post('/{id}/fail', [PaymentController::class, 'action'])->defaults('action', 'fail')->middleware('permission:payments.failure');
                    Route::post('/{id}/reject-channel', [PaymentController::class, 'action'])->defaults('action', 'reject_channel')->middleware('permission:payments.failure');
                    Route::post('/{id}/cancel', [PaymentController::class, 'action'])->defaults('action', 'cancel')->middleware('permission:payments.update');
                    Route::post('/{id}/void', [PaymentController::class, 'action'])->defaults('action', 'void')->middleware('permission:payments.update');
                    Route::post('/{id}/reverse', [PaymentController::class, 'reverse'])->middleware('permission:payments.corrections.reverse');
                    Route::post('/{id}/voucher', [PaymentController::class, 'voucher'])->middleware('permission:payments.voucher.view');
                    Route::post('/{id}/evidence', [PaymentController::class, 'uploadEvidence'])->middleware('permission:payments.evidence.upload');
                    Route::get('/{id}/evidence', [PaymentController::class, 'evidence'])->middleware('permission:payments.evidence.view');
                    Route::get('/{id}/evidence/{attachmentId}/download', [PaymentController::class, 'downloadEvidence'])->middleware('permission:payments.evidence.download');
                    Route::post('/{id}/recover', [PaymentController::class, 'recover'])->middleware('permission:payments.recovery.resolve');
                    Route::post('/{id}/allocate', [PaymentController::class, 'allocate'])->middleware('permission:payments.allocate');
                    Route::post('/{id}/allocations/{allocationId}/unapply', [PaymentController::class, 'unapply'])->middleware('permission:payments.allocations.unapply');
                    Route::post('/{id}/allocations/{allocationId}/reallocate', [PaymentController::class, 'reallocate'])->middleware('permission:payments.allocations.reallocate');
                    Route::post('/{id}/remittance', [PaymentController::class, 'remittance'])->middleware('permission:payments.remittance.view');
                    Route::get('/{id}', [PaymentController::class, 'show'])->middleware('permission:payments.view');
                });
                Route::prefix('expenses')->group(function () {
                    Route::get('/lookups', [ExpenseController::class, 'lookups'])->middleware('permission:expenses.view');
                    Route::get('/summary', [ExpenseController::class, 'summary'])->middleware('permission:expenses.view');
                    Route::get('/attention', [ExpenseController::class, 'attention'])->middleware('permission:expenses.view');
                    Route::get('/reports/{report}', [ExpenseCompletionController::class, 'report'])->middleware('permission:expenses.reports.view');
                    Route::get('/reimbursements', [ExpenseCompletionController::class, 'claims'])->middleware('permission:expenses.reimbursements.view');
                    Route::post('/reimbursements', [ExpenseCompletionController::class, 'storeClaim'])->middleware('permission:expenses.reimbursements.create');
                    Route::get('/reimbursements/{id}', [ExpenseCompletionController::class, 'claim'])->middleware('permission:expenses.reimbursements.view');
                    Route::post('/reimbursements/{id}/submit', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'submit')->middleware('permission:expenses.reimbursements.create');
                    Route::post('/reimbursements/{id}/approve', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'approve')->middleware('permission:expenses.reimbursements.approve');
                    Route::post('/reimbursements/{id}/reject', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'reject')->middleware('permission:expenses.reimbursements.approve');
                    Route::post('/reimbursements/{id}/return', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'return')->middleware('permission:expenses.reimbursements.approve');
                    Route::post('/reimbursements/{id}/post', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'post')->middleware('permission:expenses.post');
                    Route::post('/reimbursements/{id}/cancel', [ExpenseCompletionController::class, 'claimAction'])->defaults('action', 'cancel')->middleware('permission:expenses.reimbursements.create');
                    Route::post('/reimbursements/{id}/pay', [ExpenseCompletionController::class, 'payClaim'])->middleware('permission:expenses.reimbursements.payment.request');
                    Route::get('/recurring', [ExpenseCompletionController::class, 'templates'])->middleware('permission:expenses.recurring.view');
                    Route::post('/recurring', [ExpenseCompletionController::class, 'storeTemplate'])->middleware('permission:expenses.recurring.manage');
                    Route::post('/recurring/{id}/generate', [ExpenseCompletionController::class, 'generateTemplate'])->middleware('permission:expenses.recurring.manage');
                    Route::patch('/recurring/{id}', [ExpenseCompletionController::class, 'toggleTemplate'])->middleware('permission:expenses.recurring.manage');
                    Route::get('/corrections', [ExpenseCompletionController::class, 'corrections'])->middleware('permission:expenses.corrections.create');
                    Route::post('/{id}/copy', [ExpenseCompletionController::class, 'copy'])->middleware('permission:expenses.copy');
                    Route::post('/{id}/correction', [ExpenseCompletionController::class, 'correction'])->middleware('permission:expenses.corrections.create');
                    Route::post('/corrections/{id}/link-refund', [ExpenseCompletionController::class, 'linkRefund'])->middleware('permission:expenses.corrections.create');
                    Route::post('/import/preview', [ExpenseCompletionController::class, 'previewImport'])->middleware('permission:expenses.import');
                    Route::post('/import/{id}/apply', [ExpenseCompletionController::class, 'applyImport'])->middleware('permission:expenses.import');
                    Route::get('/history', [ExpenseController::class, 'history'])->middleware('permission:expenses.history');
                    Route::get('/unpaid', [ExpenseController::class, 'unpaid'])->middleware('permission:expenses.unpaid.view');
                    Route::get('/obligations', [ExpenseController::class, 'obligations'])->middleware('permission:expenses.obligations.view');
                    Route::post('/calculate', [ExpenseController::class, 'calculate'])->middleware('permission:expenses.create');
                    Route::get('/', [ExpenseController::class, 'index'])->middleware('permission:expenses.view');
                    Route::post('/', [ExpenseController::class, 'store'])->middleware('permission:expenses.create');
                    Route::get('/obligations/{id}', [ExpenseController::class, 'obligation'])->middleware('permission:expenses.obligations.view');
                    Route::get('/{id}', [ExpenseController::class, 'show'])->middleware('permission:expenses.view');
                    Route::patch('/{id}', [ExpenseController::class, 'update'])->middleware('permission:expenses.update');
                    Route::post('/{id}/submit', [ExpenseController::class, 'action'])->defaults('action', 'submit')->middleware('permission:expenses.submit');
                    Route::post('/{id}/review', [ExpenseController::class, 'action'])->defaults('action', 'review')->middleware('permission:expenses.review');
                    Route::post('/{id}/approve', [ExpenseController::class, 'action'])->defaults('action', 'approve')->middleware('permission:expenses.approve');
                    Route::post('/{id}/reject', [ExpenseController::class, 'action'])->defaults('action', 'reject')->middleware('permission:expenses.reject');
                    Route::post('/{id}/return', [ExpenseController::class, 'action'])->defaults('action', 'return')->middleware('permission:expenses.return');
                    Route::post('/{id}/post', [ExpenseController::class, 'action'])->defaults('action', 'post')->middleware('permission:expenses.post');
                    Route::post('/{id}/cancel', [ExpenseController::class, 'action'])->defaults('action', 'cancel')->middleware('permission:expenses.cancel');
                    Route::post('/{id}/close', [ExpenseController::class, 'action'])->defaults('action', 'close')->middleware('permission:expenses.post');
                    Route::post('/{id}/pay', [ExpenseController::class, 'pay'])->middleware('permission:expenses.payment.request');
                    Route::post('/{id}/evidence', [ExpenseController::class, 'uploadEvidence'])->middleware('permission:expenses.evidence.upload');
                    Route::get('/{id}/evidence', [ExpenseController::class, 'evidence'])->middleware('permission:expenses.evidence.view');
                    Route::get('/{id}/evidence/{attachmentId}/download', [ExpenseController::class, 'downloadEvidence'])->middleware('permission:expenses.evidence.view');
                });
                Route::prefix('purchases')->group(function () {
                    Route::get('/lookups', [PurchasingController::class, 'lookups'])->middleware('permission:purchases.view');
                    Route::get('/summary', [PurchasingController::class, 'summary'])->middleware('permission:purchases.view');
                    Route::get('/history', [PurchasingController::class, 'history'])->middleware('permission:purchases.history');
                    Route::get('/attention', [PurchasingController::class, 'attention'])->middleware('permission:purchases.view');
                    Route::get('/reports/{report}', [PurchasingController::class, 'report'])->middleware('permission:purchases.reports.view');
                    Route::get('/ledger/{supplierId}', [PurchasingController::class, 'ledger'])->middleware('permission:purchases.ledger.view');
                    Route::get('/payables/aging', [PurchasingController::class, 'aging'])->middleware('permission:purchases.payables.aging.view');
                    Route::get('/payables/{id}/effects', [PurchasingController::class, 'payableEffects'])->middleware('permission:purchases.payables.effects.view');
                    Route::post('/payables/{id}/hold', [PurchasingController::class, 'payableHold'])->defaults('action', 'hold')->middleware('permission:purchases.payables.hold');
                    Route::post('/payables/{id}/dispute', [PurchasingController::class, 'payableHold'])->defaults('action', 'dispute')->middleware('permission:purchases.payables.hold');
                    Route::post('/payables/{id}/release', [PurchasingController::class, 'payableHold'])->defaults('action', 'release')->middleware('permission:purchases.payables.release');
                    Route::get('/payables', [PurchasingController::class, 'payables'])->middleware('permission:purchases.payables.view');
                    Route::get('/payables/{id}', [PurchasingController::class, 'payable'])->middleware('permission:purchases.payables.view');
                    Route::get('/returns/eligible-lines', [PurchasingController::class, 'eligibleReturnLines'])->middleware('permission:purchases.returns.view');
                    Route::get('/returns', [PurchasingController::class, 'returns'])->middleware('permission:purchases.returns.view');
                    Route::post('/returns', [PurchasingController::class, 'storeReturn'])->middleware('permission:purchases.returns.create');
                    Route::get('/returns/{id}', [PurchasingController::class, 'showReturn'])->middleware('permission:purchases.returns.view');
                    Route::post('/returns/{id}/submit', [PurchasingController::class, 'returnAction'])->defaults('action', 'submit')->middleware('permission:purchases.returns.submit');
                    Route::post('/returns/{id}/review', [PurchasingController::class, 'returnAction'])->defaults('action', 'review')->middleware('permission:purchases.returns.review');
                    Route::post('/returns/{id}/approve', [PurchasingController::class, 'returnAction'])->defaults('action', 'approve')->middleware('permission:purchases.returns.approve');
                    Route::post('/returns/{id}/post', [PurchasingController::class, 'returnAction'])->defaults('action', 'post')->middleware('permission:purchases.returns.post');
                    Route::post('/returns/{id}/reverse', [PurchasingController::class, 'returnAction'])->defaults('action', 'reverse')->middleware('permission:purchases.returns.reverse');
                    Route::post('/returns/{id}/cancel', [PurchasingController::class, 'returnAction'])->defaults('action', 'cancel')->middleware('permission:purchases.returns.update');
                    Route::get('/adjustments', [PurchasingController::class, 'adjustments'])->middleware('permission:purchases.adjustments.view');
                    Route::post('/adjustments', [PurchasingController::class, 'storeAdjustment'])->middleware('permission:purchases.adjustments.create');
                    Route::get('/adjustments/{id}', [PurchasingController::class, 'showAdjustment'])->middleware('permission:purchases.adjustments.view');
                    Route::post('/adjustments/{id}/submit', [PurchasingController::class, 'adjustmentAction'])->defaults('action', 'submit')->middleware('permission:purchases.adjustments.submit');
                    Route::post('/adjustments/{id}/approve', [PurchasingController::class, 'adjustmentAction'])->defaults('action', 'approve')->middleware('permission:purchases.adjustments.approve');
                    Route::post('/adjustments/{id}/post', [PurchasingController::class, 'adjustmentAction'])->defaults('action', 'post')->middleware('permission:purchases.adjustments.post');
                    Route::post('/adjustments/{id}/reverse', [PurchasingController::class, 'adjustmentAction'])->defaults('action', 'reverse')->middleware('permission:purchases.adjustments.reverse');
                    Route::post('/match-exceptions/{id}/resolve', [PurchasingController::class, 'resolveMatchException'])->middleware('permission:purchases.matches.resolve');
                    Route::get('/orders', [PurchasingController::class, 'orders'])->middleware('permission:purchases.orders.view');
                    Route::post('/orders', [PurchasingController::class, 'storeOrder'])->middleware('permission:purchases.orders.create');
                    Route::get('/orders/{id}', [PurchasingController::class, 'showOrder'])->middleware('permission:purchases.orders.view');
                    Route::patch('/orders/{id}', [PurchasingController::class, 'updateOrder'])->middleware('permission:purchases.orders.update');
                    Route::patch('/orders/{id}/amend', [PurchasingController::class, 'amendOrder'])->middleware('permission:purchases.orders.amend');
                    Route::post('/orders/{id}/reopen', [PurchasingController::class, 'reopenOrder'])->middleware('permission:purchases.orders.reopen');
                    Route::post('/orders/{id}/submit', [PurchasingController::class, 'orderAction'])->defaults('action', 'submit')->middleware('permission:purchases.orders.submit');
                    Route::post('/orders/{id}/review', [PurchasingController::class, 'orderAction'])->defaults('action', 'review')->middleware('permission:purchases.orders.review');
                    Route::post('/orders/{id}/approve', [PurchasingController::class, 'orderAction'])->defaults('action', 'approve')->middleware('permission:purchases.orders.approve');
                    Route::post('/orders/{id}/cancel', [PurchasingController::class, 'orderAction'])->defaults('action', 'cancel')->middleware('permission:purchases.orders.cancel');
                    Route::post('/orders/{id}/close', [PurchasingController::class, 'orderAction'])->defaults('action', 'close')->middleware('permission:purchases.orders.close');
                    Route::get('/orders/{id}/history', [PurchasingController::class, 'orderHistory'])->middleware('permission:purchases.history');
                    Route::get('/receipts', [PurchasingController::class, 'receipts'])->middleware('permission:purchases.receipts.view');
                    Route::post('/receipts', [PurchasingController::class, 'storeReceipt'])->middleware('permission:purchases.receipts.create');
                    Route::get('/receipts/{id}', [PurchasingController::class, 'showReceipt'])->middleware('permission:purchases.receipts.view');
                    Route::post('/receipts/{id}/submit', [PurchasingController::class, 'receiptAction'])->defaults('action', 'submit')->middleware('permission:purchases.receipts.submit');
                    Route::post('/receipts/{id}/post', [PurchasingController::class, 'receiptAction'])->defaults('action', 'post')->middleware('permission:purchases.receipts.post');
                    Route::post('/receipts/{id}/reverse', [PurchasingController::class, 'receiptAction'])->defaults('action', 'reverse')->middleware('permission:purchases.receipts.reverse');
                    Route::get('/invoices', [PurchasingController::class, 'invoices'])->middleware('permission:purchases.invoices.view');
                    Route::post('/invoices', [PurchasingController::class, 'storeInvoice'])->middleware('permission:purchases.invoices.create');
                    Route::get('/invoices/{id}', [PurchasingController::class, 'showInvoice'])->middleware('permission:purchases.invoices.view');
                    Route::post('/invoices/{id}/correction', [PurchasingController::class, 'storeInvoiceCorrection'])->middleware('permission:purchases.invoices.correction.create');
                    Route::get('/invoice-corrections/{id}', [PurchasingController::class, 'showInvoiceCorrection'])->middleware('permission:purchases.invoices.correction.view');
                    Route::get('/invoice-corrections', [PurchasingController::class, 'invoiceCorrections'])->middleware('permission:purchases.invoices.correction.view');
                    Route::post('/invoice-corrections/{id}/submit', [PurchasingController::class, 'invoiceCorrectionAction'])->defaults('action', 'submit')->middleware('permission:purchases.invoices.correction.create');
                    Route::post('/invoice-corrections/{id}/approve', [PurchasingController::class, 'invoiceCorrectionAction'])->defaults('action', 'approve')->middleware('permission:purchases.invoices.correction.post');
                    Route::post('/invoice-corrections/{id}/post', [PurchasingController::class, 'invoiceCorrectionAction'])->defaults('action', 'post')->middleware('permission:purchases.invoices.correction.post');
                    Route::post('/invoice-corrections/{id}/reverse', [PurchasingController::class, 'invoiceCorrectionAction'])->defaults('action', 'reverse')->middleware('permission:purchases.invoices.reverse');
                    Route::post('/invoices/{id}/submit', [PurchasingController::class, 'invoiceAction'])->defaults('action', 'submit')->middleware('permission:purchases.invoices.submit');
                    Route::post('/invoices/{id}/approve', [PurchasingController::class, 'invoiceAction'])->defaults('action', 'approve')->middleware('permission:purchases.invoices.approve');
                    Route::post('/invoices/{id}/post', [PurchasingController::class, 'invoiceAction'])->defaults('action', 'post')->middleware('permission:purchases.invoices.post');
                    Route::post('/invoices/{id}/reverse', [PurchasingController::class, 'invoiceAction'])->defaults('action', 'reverse')->middleware('permission:purchases.invoices.reverse');
                });
                Route::prefix('sales')->group(function () {
                    Route::get('/lookups', [SalesController::class, 'lookups'])->middleware('permission:sales.view');
                    Route::get('/summary', [SalesController::class, 'summary'])->middleware('permission:sales.view');
                    Route::get('/', [SalesController::class, 'index'])->middleware('permission:sales.view');
                    Route::post('/', [SalesController::class, 'store'])->middleware('permission:sales.create');
                    Route::get('/{id}', [SalesController::class, 'show'])->middleware('permission:sales.view');
                    Route::patch('/{id}', [SalesController::class, 'update'])->middleware('permission:sales.update');
                    Route::post('/{id}/submit', [SalesController::class, 'action'])->defaults('action', 'submit')->middleware('permission:sales.submit');
                    Route::post('/{id}/review', [SalesController::class, 'action'])->defaults('action', 'review')->middleware('permission:sales.review');
                    Route::post('/{id}/return', [SalesController::class, 'action'])->defaults('action', 'return')->middleware('permission:sales.review');
                    Route::post('/{id}/approve', [SalesController::class, 'action'])->defaults('action', 'approve')->middleware('permission:sales.approve');
                    Route::post('/{id}/post', [SalesController::class, 'action'])->defaults('action', 'post')->middleware('permission:sales.post');
                    Route::post('/{id}/cancel', [SalesController::class, 'action'])->defaults('action', 'cancel')->middleware('permission:sales.cancel');
                    Route::get('/{id}/history', [SalesController::class, 'history'])->middleware('permission:sales.history');
                });
                Route::prefix('collections')->group(function () {
                    Route::get('/summary', [CollectionsController::class, 'summary'])->middleware('permission:collections.view');
                    Route::get('/lookups', [CollectionsController::class, 'lookups'])->middleware('permission:collections.view');
                    Route::get('/other-receipt-types', [CollectionsController::class, 'otherReceiptTypes'])->middleware('permission:collections.other_receipts.view');
                    Route::get('/other-receipts', [CollectionsController::class, 'otherReceipts'])->middleware('permission:collections.other_receipts.view');
                    Route::post('/other-receipts', [CollectionsController::class, 'storeOtherReceipt'])->middleware('permission:collections.other_receipts.create');
                    Route::post('/other-receipts/{id}/submit', [CollectionsController::class, 'otherAction'])->defaults('action', 'submit')->middleware('permission:collections.receipts.submit');
                    Route::post('/other-receipts/{id}/approve', [CollectionsController::class, 'otherAction'])->defaults('action', 'approve')->middleware('permission:collections.other_receipts.approve');
                    Route::post('/other-receipts/{id}/post', [CollectionsController::class, 'otherAction'])->defaults('action', 'post')->middleware('permission:collections.other_receipts.post');
                    Route::post('/other-receipts/{id}/reverse', [CollectionsController::class, 'otherAction'])->defaults('action', 'reverse')->middleware('permission:collections.other_receipts.reverse');
                    Route::get('/activities', [CollectionsController::class, 'activities'])->middleware('permission:collections.activities.view');
                    Route::post('/activities', [CollectionsController::class, 'storeActivity'])->middleware('permission:collections.activities.create');
                    Route::get('/remittances', [CollectionsController::class, 'remittances'])->middleware('permission:collections.remittance.view');
                    Route::post('/remittances', [CollectionsController::class, 'storeRemittance'])->middleware('permission:collections.remittance.create');
                    Route::get('/remittances/{id}', [CollectionsController::class, 'showRemittance'])->middleware('permission:collections.remittance.view');
                    Route::get('/reports/{report}', [CollectionsController::class, 'report'])->middleware('permission:collections.reports.view');
                    Route::post('/remittances/{id}/submit', [CollectionsController::class, 'remittanceAction'])->defaults('action', 'submit')->middleware('permission:collections.remittance.submit');
                    Route::post('/remittances/{id}/verify', [CollectionsController::class, 'remittanceAction'])->defaults('action', 'verify')->middleware('permission:collections.remittance.verify');
                    Route::post('/remittances/{id}/accept', [CollectionsController::class, 'remittanceAction'])->defaults('action', 'accept')->middleware('permission:collections.remittance.accept');
                    Route::post('/remittances/{id}/reject', [CollectionsController::class, 'remittanceAction'])->defaults('action', 'reject')->middleware('permission:collections.remittance.variance');
                    Route::post('/remittances/{id}/reverse', [CollectionsController::class, 'remittanceAction'])->defaults('action', 'reverse')->middleware('permission:collections.remittance.reverse');
                    Route::post('/remittance-variances/{id}/resolve', [CollectionsController::class, 'resolveVariance'])->middleware('permission:collections.remittance.resolve');
                    Route::get('/unapplied', [CollectionsController::class, 'unapplied'])->middleware('permission:collections.unapplied.view');
                    Route::get('/ledger/{customerId}', [CollectionsController::class, 'ledger'])->middleware('permission:collections.ledger.view');
                    Route::post('/applications', [CollectionsController::class, 'apply'])->middleware('permission:collections.applications.create');
                    Route::post('/applications/{id}/reverse', [CollectionsController::class, 'reverseApplication'])->middleware('permission:collections.applications.reverse');
                    Route::get('/receipts', [CollectionsController::class, 'index'])->middleware('permission:collections.view');
                    Route::post('/receipts', [CollectionsController::class, 'store'])->middleware('permission:collections.receipts.create');
                    Route::get('/receipts/{id}', [CollectionsController::class, 'show'])->middleware('permission:collections.view');
                    Route::patch('/receipts/{id}', [CollectionsController::class, 'update'])->middleware('permission:collections.receipts.update');
                    Route::post('/receipts/{id}/submit', [CollectionsController::class, 'action'])->defaults('action', 'submit')->middleware('permission:collections.receipts.submit');
                    Route::post('/receipts/{id}/review', [CollectionsController::class, 'action'])->defaults('action', 'review')->middleware('permission:collections.receipts.review');
                    Route::post('/receipts/{id}/approve', [CollectionsController::class, 'action'])->defaults('action', 'approve')->middleware('permission:collections.receipts.approve');
                    Route::post('/receipts/{id}/post', [CollectionsController::class, 'action'])->defaults('action', 'post')->middleware('permission:collections.receipts.post');
                    Route::post('/receipts/{id}/cancel', [CollectionsController::class, 'action'])->defaults('action', 'cancel')->middleware('permission:collections.receipts.cancel');
                    Route::post('/receipts/{id}/reverse', [CollectionsController::class, 'action'])->defaults('action', 'reverse')->middleware('permission:collections.receipts.reverse');
                    Route::post('/receipts/{id}/reprint', [CollectionsController::class, 'reprint'])->middleware('permission:collections.receipts.reprint');
                    Route::get('/receipts/{id}/print', [CollectionsController::class, 'printable'])->middleware('permission:collections.receipts.print');
                    Route::get('/receipts/{id}/history', [CollectionsController::class, 'history'])->middleware('permission:collections.history.view');
                    Route::post('/tenders/{id}/fail', [CollectionsController::class, 'failTender'])->middleware('permission:collections.instruments.fail');
                });
                Route::prefix('receivables')->group(function () {
                    Route::get('/', [SalesController::class, 'receivables'])->middleware('permission:sales.receivables.view');
                    Route::get('/aging', [SalesController::class, 'aging'])->middleware('permission:sales.receivables.aging.view');
                    Route::get('/{id}', [SalesController::class, 'receivable'])->middleware('permission:sales.receivables.view');
                });
                Route::prefix('billing-statements')->group(function () {
                    Route::get('/', [SalesController::class, 'statements'])->middleware('permission:sales.billing-statements.view');
                    Route::post('/', [SalesController::class, 'storeStatement'])->middleware('permission:sales.billing-statements.create');
                    Route::get('/{id}', [SalesController::class, 'statement'])->middleware('permission:sales.billing-statements.view');
                });
                Route::prefix('inventory')->group(function () {
                    Route::get('/summary', [InventoryController::class, 'summary'])->middleware('permission:inventory.view');
                    Route::get('/lookups', [InventoryController::class, 'lookups'])->middleware('permission:inventory.view');
                    Route::get('/balances', [InventoryController::class, 'balances'])->middleware('permission:inventory.balances.view');
                    Route::get('/movements', [InventoryController::class, 'movements'])->middleware('permission:inventory.movements.view');
                    Route::get('/availability/{productId}', [InventoryController::class, 'availability'])->middleware('permission:inventory.balances.view');
                    Route::post('/opening-stock', [InventoryController::class, 'storeOpening'])->middleware('permission:inventory.opening-stock.create');
                    Route::patch('/opening-stock/{id}', [InventoryController::class, 'updateOpeningStock'])->middleware('permission:inventory.opening-stock.update');
                    Route::post('/opening-stock/{id}/post', [InventoryController::class, 'postOpeningStock'])->middleware('permission:inventory.opening-stock.post');
                    Route::post('/opening-stock/{id}/reverse', [InventoryController::class, 'reverseOpeningStock'])->middleware('permission:inventory.opening-stock.reverse');
                    Route::get('/opening-stock/{id}', [InventoryController::class, 'showOpeningStock'])->middleware('permission:inventory.view');
                    Route::post('/receipts', [InventoryController::class, 'storeReceipt'])->middleware('permission:inventory.receipts.create');
                    Route::patch('/receipts/{id}', [InventoryController::class, 'updateReceipt'])->middleware('permission:inventory.receipts.update');
                    Route::post('/receipts/{id}/post', [InventoryController::class, 'postReceipt'])->middleware('permission:inventory.receipts.post');
                    Route::post('/receipts/{id}/reverse', [InventoryController::class, 'reverseReceipt'])->middleware('permission:inventory.receipts.reverse');
                    Route::get('/receipts/{id}', [InventoryController::class, 'showReceipt'])->middleware('permission:inventory.view');
                    Route::post('/issues', [InventoryController::class, 'storeIssue'])->middleware('permission:inventory.issues.create');
                    Route::patch('/issues/{id}', [InventoryController::class, 'updateIssue'])->middleware('permission:inventory.issues.update');
                    Route::post('/issues/{id}/post', [InventoryController::class, 'postIssue'])->middleware('permission:inventory.issues.post');
                    Route::post('/issues/{id}/reverse', [InventoryController::class, 'reverseIssue'])->middleware('permission:inventory.issues.reverse');
                    Route::get('/issues/{id}', [InventoryController::class, 'showIssue'])->middleware('permission:inventory.view');
                    Route::post('/transfers', [InventoryController::class, 'storeTransfer'])->middleware('permission:inventory.transfers.create');
                    Route::patch('/transfers/{id}', [InventoryController::class, 'updateTransfer'])->middleware('permission:inventory.transfers.update');
                    Route::post('/transfers/{id}/post', [InventoryController::class, 'postTransfer'])->middleware('permission:inventory.transfers.post');
                    Route::post('/transfers/{id}/reverse', [InventoryController::class, 'reverseTransfer'])->middleware('permission:inventory.transfers.reverse');
                    Route::get('/transfers/{id}', [InventoryController::class, 'showTransfer'])->middleware('permission:inventory.transfers.view');
                    Route::get('/adjustments', [InventoryController::class, 'adjustments'])->middleware('permission:inventory.adjustments.view');
                    Route::post('/adjustments', [InventoryController::class, 'storeAdjustment'])->middleware('permission:inventory.adjustments.create');
                    Route::get('/adjustments/{id}', [InventoryController::class, 'showAdjustment'])->middleware('permission:inventory.adjustments.view');
                    Route::patch('/adjustments/{id}', [InventoryController::class, 'updateAdjustment'])->middleware('permission:inventory.adjustments.update');
                    Route::post('/adjustments/{id}/submit', [InventoryController::class, 'adjustmentAction'])->defaults('action', 'submit')->middleware('permission:inventory.adjustments.submit');
                    Route::post('/adjustments/{id}/review', [InventoryController::class, 'adjustmentAction'])->defaults('action', 'review')->middleware('permission:inventory.adjustments.review');
                    Route::post('/adjustments/{id}/approve', [InventoryController::class, 'adjustmentAction'])->defaults('action', 'approve')->middleware('permission:inventory.adjustments.approve');
                    Route::post('/adjustments/{id}/post', [InventoryController::class, 'adjustmentAction'])->defaults('action', 'post')->middleware('permission:inventory.adjustments.post');
                    Route::post('/adjustments/{id}/cancel', [InventoryController::class, 'adjustmentAction'])->defaults('action', 'cancel')->middleware('permission:inventory.adjustments.update');
                    Route::post('/adjustments/{id}/reverse', [InventoryController::class, 'reverseAdjustment'])->middleware('permission:inventory.adjustments.reverse');
                    Route::get('/counts', [InventoryController::class, 'counts'])->middleware('permission:inventory.counts.view');
                    Route::post('/counts', [InventoryController::class, 'storeCount'])->middleware('permission:inventory.counts.create');
                    Route::get('/counts/{id}', [InventoryController::class, 'showCount'])->middleware('permission:inventory.counts.view');
                    Route::post('/counts/{id}/start', [InventoryController::class, 'startCount'])->middleware('permission:inventory.counts.start');
                    Route::post('/counts/{id}/entries', [InventoryController::class, 'countEntry'])->middleware('permission:inventory.counts.entries');
                    Route::post('/counts/{id}/recount', [InventoryController::class, 'countRecount'])->middleware('permission:inventory.counts.recount');
                    Route::post('/counts/{id}/submit', [InventoryController::class, 'countAction'])->defaults('action', 'submit')->middleware('permission:inventory.counts.review');
                    Route::post('/counts/{id}/review', [InventoryController::class, 'countAction'])->defaults('action', 'review')->middleware('permission:inventory.counts.review');
                    Route::post('/counts/{id}/approve', [InventoryController::class, 'countAction'])->defaults('action', 'approve')->middleware('permission:inventory.counts.approve');
                    Route::post('/counts/{id}/post', [InventoryController::class, 'countAction'])->defaults('action', 'post')->middleware('permission:inventory.counts.post');
                    Route::post('/counts/{id}/close', [InventoryController::class, 'countAction'])->defaults('action', 'close')->middleware('permission:inventory.counts.close');
                    Route::post('/counts/{id}/reopen', [InventoryController::class, 'countAction'])->defaults('action', 'reopen')->middleware('permission:inventory.counts.reopen');
                    Route::post('/counts/{id}/cancel', [InventoryController::class, 'countAction'])->defaults('action', 'cancel')->middleware('permission:inventory.counts.cancel');
                    Route::get('/reservations', [InventoryController::class, 'reservations'])->middleware('permission:inventory.reservations.view');
                    Route::post('/reservations', [InventoryController::class, 'storeReservation'])->middleware('permission:inventory.reservations.create');
                    Route::get('/reservations/{id}', [InventoryController::class, 'showReservation'])->middleware('permission:inventory.reservations.view');
                    Route::post('/reservations/{id}/consume', [InventoryController::class, 'reservationAction'])->defaults('action', 'consume')->middleware('permission:inventory.reservations.consume');
                    Route::post('/reservations/{id}/release', [InventoryController::class, 'reservationAction'])->defaults('action', 'release')->middleware('permission:inventory.reservations.release');
                    Route::post('/reservations/{id}/expire', [InventoryController::class, 'reservationAction'])->defaults('action', 'expire')->middleware('permission:inventory.reservations.expire');
                    Route::get('/reorder-rules', [InventoryController::class, 'reorderRules'])->middleware('permission:inventory.reorder.view');
                    Route::post('/reorder-rules', [InventoryController::class, 'storeReorderRule'])->middleware('permission:inventory.reorder.manage');
                    Route::patch('/reorder-rules/{id}', [InventoryController::class, 'updateReorderRule'])->middleware('permission:inventory.reorder.manage');
                    Route::delete('/reorder-rules/{id}', [InventoryController::class, 'deleteReorderRule'])->middleware('permission:inventory.reorder.manage');
                    Route::get('/attention', [InventoryController::class, 'attention'])->middleware('permission:inventory.view');
                    Route::get('/stock-card', [InventoryController::class, 'stockCard'])->middleware('permission:inventory.stock-card.view');
                    Route::get('/reports/{report}', [InventoryController::class, 'report'])->middleware('permission:inventory.reports.view');
                    Route::get('/barcode/{barcode}', [InventoryController::class, 'barcode'])->middleware('permission:inventory.barcode.lookup');
                });
                Route::get('/settings/company', [CompanyProfileController::class, 'show'])->middleware('permission:settings.company.view');
                Route::patch('/settings/company', [CompanyProfileController::class, 'update'])->middleware('permission:settings.company.edit');
                Route::get('/settings/users', [UserAccessController::class, 'index'])->middleware('permission:settings.users.view');
                Route::get('/settings/users/roles', [UserAccessController::class, 'roles'])->middleware('permission:settings.users.view');
                Route::get('/settings/users/invitations', [UserAccessController::class, 'invitations'])->middleware('permission:settings.users.view');
                Route::post('/settings/users/invitations', [UserAccessController::class, 'invite'])->middleware('permission:settings.users.invite')->middleware('throttle:admin');
                Route::post('/settings/users/invitations/{invitation}/resend', [UserAccessController::class, 'resend'])->middleware('permission:settings.users.invite')->middleware('throttle:admin');
                Route::post('/settings/users/invitations/{invitation}/cancel', [UserAccessController::class, 'cancel'])->middleware('permission:settings.users.manage');
                Route::patch('/settings/users/{user}/role', [UserAccessController::class, 'changeRole'])->middleware('permission:settings.users.manage');
                Route::patch('/settings/users/{user}/status/{status}', [UserAccessController::class, 'changeStatus'])->middleware('permission:settings.users.manage');
                Route::get('/settings/activity', [UserAccessController::class, 'activity'])->middleware('permission:settings.activity.view');

                Route::prefix('cash-accounts')->group(function () {
                    Route::get('/types', [CashAccountController::class, 'types'])->middleware('permission:cash-accounts.accounts.view');
                    Route::get('/lookups', [CashAccountController::class, 'lookups'])->middleware('permission:cash-accounts.search');
                    Route::get('/summary', [CashAccountController::class, 'summary'])->middleware('permission:cash-accounts.view');
                    Route::get('/needs-attention', [CashAccountController::class, 'needsAttention'])->middleware('permission:cash-accounts.view');
                    Route::get('/movement-purposes', [CashMovementController::class, 'purposes'])->middleware('permission:cash-accounts.movements.view');
                    Route::get('/movements', [CashMovementController::class, 'movementHistory'])->middleware('permission:cash-accounts.movements.history');
                    Route::get('/statement-imports', [StatementImportController::class, 'index'])->middleware('permission:cash-accounts.statements.view');
                    Route::post('/statement-imports', [StatementImportController::class, 'store'])->middleware('permission:cash-accounts.statements.import');
                    Route::get('/statement-imports/{id}', [StatementImportController::class, 'show'])->middleware('permission:cash-accounts.statements.view');
                    Route::post('/statement-imports/{id}/evidence', [StatementImportController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.statements.import');
                    Route::get('/statement-imports/{id}/evidence', [StatementImportController::class, 'evidence'])->middleware('permission:cash-accounts.statements.evidence.view');
                    Route::post('/statement-imports/{id}/lines', [StatementImportController::class, 'addLine'])->middleware('permission:cash-accounts.statements.import');
                    Route::post('/statement-imports/{id}/validate', [StatementImportController::class, 'validateBatch'])->middleware('permission:cash-accounts.statements.validate');
                    Route::post('/statement-imports/{id}/cancel', [StatementImportController::class, 'cancel'])->middleware('permission:cash-accounts.statements.cancel');
                    Route::get('/reconciliations', [ReconciliationController::class, 'index'])->middleware('permission:cash-accounts.reconciliations.view');
                    Route::post('/reconciliations', [ReconciliationController::class, 'store'])->middleware('permission:cash-accounts.reconciliations.create');
                    Route::get('/reconciliations/{id}', [ReconciliationController::class, 'show'])->middleware('permission:cash-accounts.reconciliations.view');
                    Route::post('/reconciliations/{id}/refresh', [ReconciliationController::class, 'refresh'])->middleware('permission:cash-accounts.reconciliations.update');
                    Route::get('/reconciliations/{id}/candidates', [ReconciliationController::class, 'candidates'])->middleware('permission:cash-accounts.reconciliation.matches.view');
                    Route::post('/reconciliations/{id}/matches', [ReconciliationController::class, 'match'])->middleware('permission:cash-accounts.reconciliation.matches.create');
                    Route::post('/reconciliations/{id}/outstanding-items', [ReconciliationController::class, 'outstanding'])->middleware('permission:cash-accounts.reconciliations.update');
                    Route::post('/reconciliations/{id}/prepare', [ReconciliationController::class, 'action'])->defaults('action', 'prepare')->middleware('permission:cash-accounts.reconciliations.prepare');
                    Route::post('/reconciliations/{id}/submit', [ReconciliationController::class, 'action'])->defaults('action', 'submit')->middleware('permission:cash-accounts.reconciliations.submit');
                    Route::post('/reconciliations/{id}/review', [ReconciliationController::class, 'action'])->defaults('action', 'review')->middleware('permission:cash-accounts.reconciliations.review');
                    Route::post('/reconciliations/{id}/return', [ReconciliationController::class, 'action'])->defaults('action', 'return')->middleware('permission:cash-accounts.reconciliations.review');
                    Route::post('/reconciliations/{id}/approve', [ReconciliationController::class, 'action'])->defaults('action', 'approve')->middleware('permission:cash-accounts.reconciliations.approve');
                    Route::post('/reconciliations/{id}/complete', [ReconciliationController::class, 'action'])->defaults('action', 'complete')->middleware('permission:cash-accounts.reconciliations.complete');
                    Route::post('/reconciliations/{id}/reopen', [ReconciliationController::class, 'action'])->defaults('action', 'reopen')->middleware('permission:cash-accounts.reconciliations.reopen');
                    Route::post('/reconciliations/{id}/cancel', [ReconciliationController::class, 'action'])->defaults('action', 'cancel')->middleware('permission:cash-accounts.reconciliations.cancel');
                    Route::get('/reconciliations/{id}/history', [ReconciliationController::class, 'history'])->middleware('permission:cash-accounts.reconciliations.view');
                    Route::post('/reconciliation-matches/{matchId}/unmatch', [ReconciliationController::class, 'unmatch'])->middleware('permission:cash-accounts.reconciliation.matches.unmatch');
                    Route::post('/reconciliation-adjustments', [ReconciliationAdjustmentController::class, 'store'])->middleware('permission:cash-accounts.reconciliation-adjustments.create');
                    Route::get('/reconciliation-adjustments/{id}', [ReconciliationAdjustmentController::class, 'show'])->middleware('permission:cash-accounts.reconciliations.view');
                    Route::post('/reconciliation-adjustments/{id}/evidence', [ReconciliationAdjustmentController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.reconciliation-adjustments.create');
                    Route::post('/reconciliation-adjustments/{id}/submit', [ReconciliationAdjustmentController::class, 'action'])->defaults('action', 'submit')->middleware('permission:cash-accounts.reconciliation-adjustments.review');
                    Route::post('/reconciliation-adjustments/{id}/approve', [ReconciliationAdjustmentController::class, 'action'])->defaults('action', 'approve')->middleware('permission:cash-accounts.reconciliation-adjustments.approve');
                    Route::post('/reconciliation-adjustments/{id}/post', [ReconciliationAdjustmentController::class, 'action'])->defaults('action', 'post')->middleware('permission:cash-accounts.reconciliation-adjustments.post');
                    Route::post('/reconciliation-adjustments/{id}/reverse', [ReconciliationAdjustmentController::class, 'action'])->defaults('action', 'reverse')->middleware('permission:cash-accounts.reconciliation-adjustments.reverse');
                    Route::get('/cash-counts/types', [CashCountController::class, 'types'])->middleware('permission:cash-accounts.cash-counts.view');
                    Route::get('/cash-counts/denominations', [CashCountController::class, 'denominations'])->middleware('permission:cash-accounts.denominations.view');
                    Route::post('/cash-counts/denominations', [CashCountController::class, 'storeDenomination'])->middleware('permission:cash-accounts.denominations.manage');
                    Route::get('/cash-counts/reports', [CashCountController::class, 'reports'])->middleware('permission:cash-accounts.cash-counts.reports.view');
                    Route::get('/cash-counts', [CashCountController::class, 'index'])->middleware('permission:cash-accounts.cash-counts.view');
                    Route::post('/cash-counts', [CashCountController::class, 'store'])->middleware('permission:cash-accounts.cash-counts.create');
                    Route::get('/cash-counts/{id}', [CashCountController::class, 'show'])->middleware('permission:cash-accounts.cash-counts.view');
                    Route::post('/cash-counts/{id}/start', [CashCountController::class, 'start'])->middleware('permission:cash-accounts.cash-counts.start');
                    Route::post('/cash-counts/{id}/attempts', [CashCountController::class, 'createAttempt'])->middleware('permission:cash-accounts.cash-counts.attempts');
                    Route::patch('/cash-counts/{id}/attempts/{attemptId}', [CashCountController::class, 'saveAttempt'])->middleware('permission:cash-accounts.cash-counts.attempts');
                    Route::post('/cash-counts/{id}/attempts/{attemptId}/confirm', [CashCountController::class, 'confirm'])->middleware('permission:cash-accounts.cash-counts.attempts');
                    Route::post('/cash-counts/{id}/attempts/{attemptId}/submit', [CashCountController::class, 'submitAttempt'])->middleware('permission:cash-accounts.cash-counts.submit');
                    Route::post('/cash-counts/{id}/review', [CashCountController::class, 'review'])->middleware('permission:cash-accounts.cash-counts.review');
                    Route::post('/cash-counts/{id}/approve', [CashCountController::class, 'approve'])->middleware('permission:cash-accounts.cash-counts.approve');
                    Route::post('/cash-counts/{id}/disposition', [CashCountController::class, 'disposition'])->middleware('permission:cash-accounts.variances.disposition');
                    Route::post('/cash-counts/{id}/recount', [CashCountController::class, 'recount'])->middleware('permission:cash-accounts.cash-counts.recount');
                    Route::post('/cash-counts/{id}/close', [CashCountController::class, 'close'])->middleware('permission:cash-accounts.cash-counts.approve');
                    Route::post('/cash-counts/{id}/cancel', [CashCountController::class, 'cancel'])->middleware('permission:cash-accounts.cash-counts.cancel');
                    Route::post('/cash-counts/{id}/evidence', [CashCountController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.cash-counts.evidence.upload');
                    Route::get('/cash-counts/{id}/evidence', [CashCountController::class, 'evidence'])->middleware('permission:cash-accounts.cash-counts.evidence.view');
                    Route::post('/cash-adjustments/{adjustmentId}/approve', [CashCountController::class, 'approveAdjustment'])->middleware('permission:cash-accounts.adjustments.approve');
                    Route::post('/cash-adjustments/{adjustmentId}/post', [CashCountController::class, 'postAdjustment'])->middleware('permission:cash-accounts.adjustments.post');
                    Route::post('/cash-adjustments/{adjustmentId}/reverse', [CashCountController::class, 'reverseAdjustment'])->middleware('permission:cash-accounts.adjustments.reverse');
                    Route::get('/custodian-handovers', [CashCustodianHandoverController::class, 'index'])->middleware('permission:cash-accounts.handovers.view');
                    Route::post('/custodian-handovers', [CashCustodianHandoverController::class, 'store'])->middleware('permission:cash-accounts.handovers.create');
                    Route::get('/custodian-handovers/{id}', [CashCustodianHandoverController::class, 'show'])->middleware('permission:cash-accounts.handovers.view');
                    Route::post('/custodian-handovers/{id}/confirm', [CashCustodianHandoverController::class, 'confirm'])->middleware('permission:cash-accounts.handovers.confirm');
                    Route::post('/custodian-handovers/{id}/approve', [CashCustodianHandoverController::class, 'approve'])->middleware('permission:cash-accounts.handovers.approve');
                    Route::post('/custodian-handovers/{id}/complete', [CashCustodianHandoverController::class, 'complete'])->middleware('permission:cash-accounts.handovers.complete');
                    Route::post('/custodian-handovers/{id}/cancel', [CashCustodianHandoverController::class, 'cancel'])->middleware('permission:cash-accounts.handovers.cancel');
                    Route::post('/custodian-handovers/{id}/evidence', [CashCustodianHandoverController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.cash-counts.evidence.upload');
                    Route::get('/custodian-handovers/{id}/evidence', [CashCustodianHandoverController::class, 'evidence'])->middleware('permission:cash-accounts.cash-counts.evidence.view');
                    Route::get('/cash-in', [CashMovementController::class, 'index'])->defaults('kind', 'cash_in')->middleware('permission:cash-accounts.movements.view');
                    Route::post('/cash-in', [CashMovementController::class, 'store'])->defaults('kind', 'cash_in')->middleware('permission:cash-accounts.cash-in.create');
                    Route::get('/cash-out', [CashMovementController::class, 'index'])->defaults('kind', 'cash_out')->middleware('permission:cash-accounts.movements.view');
                    Route::post('/cash-out', [CashMovementController::class, 'store'])->defaults('kind', 'cash_out')->middleware('permission:cash-accounts.cash-out.create');
                    Route::get('/transfers', [CashTransferController::class, 'index'])->middleware('permission:cash-accounts.transfers.view');
                    Route::post('/transfers', [CashTransferController::class, 'store'])->middleware('permission:cash-accounts.transfers.create');
                    Route::get('/', [CashAccountController::class, 'index'])->middleware('permission:cash-accounts.accounts.view');
                    Route::post('/', [CashAccountController::class, 'store'])->middleware('permission:cash-accounts.accounts.create');
                    Route::get('/opening-balances', [OpeningBalanceController::class, 'index'])->middleware('permission:cash-accounts.opening-balances.view');
                    Route::post('/opening-balances', [OpeningBalanceController::class, 'store'])->middleware('permission:cash-accounts.opening-balances.create');
                    Route::get('/opening-balances/{id}', [OpeningBalanceController::class, 'show'])->middleware('permission:cash-accounts.opening-balances.view');
                    Route::patch('/opening-balances/{id}', [OpeningBalanceController::class, 'update'])->middleware('permission:cash-accounts.opening-balances.update');
                    Route::post('/opening-balances/{id}/submit', [OpeningBalanceController::class, 'submit'])->middleware('permission:cash-accounts.opening-balances.submit');
                    Route::post('/opening-balances/{id}/approve', [OpeningBalanceController::class, 'approve'])->middleware('permission:cash-accounts.opening-balances.approve');
                    Route::post('/opening-balances/{id}/return', [OpeningBalanceController::class, 'reject'])->middleware('permission:cash-accounts.opening-balances.review');
                    Route::post('/opening-balances/{id}/post', [OpeningBalanceController::class, 'post'])->middleware('permission:cash-accounts.opening-balances.post');
                    Route::post('/opening-balances/{id}/reverse', [OpeningBalanceController::class, 'reverse'])->middleware('permission:cash-accounts.opening-balances.reverse');
                    Route::post('/opening-balances/{id}/evidence', [OpeningBalanceController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.evidence.upload');
                    Route::get('/opening-balances/{id}/evidence', [OpeningBalanceController::class, 'evidence'])->middleware('permission:cash-accounts.evidence.view');
                    Route::get('/opening-balances/{id}/evidence/{attachmentId}/download', [OpeningBalanceController::class, 'downloadEvidence'])->middleware('permission:cash-accounts.evidence.download');
                    Route::get('/opening-balances/{id}/history', [OpeningBalanceController::class, 'history'])->middleware('permission:cash-accounts.history');
                    Route::get('/cash-in/{id}', [CashMovementController::class, 'show'])->middleware('permission:cash-accounts.movements.view');
                    Route::patch('/cash-in/{id}', [CashMovementController::class, 'update'])->middleware('permission:cash-accounts.cash-in.update');
                    Route::get('/cash-out/{id}', [CashMovementController::class, 'show'])->middleware('permission:cash-accounts.movements.view');
                    Route::patch('/cash-out/{id}', [CashMovementController::class, 'update'])->middleware('permission:cash-accounts.cash-out.update');
                    Route::get('/transfers/{id}', [CashTransferController::class, 'show'])->middleware('permission:cash-accounts.transfers.view');
                    Route::patch('/transfers/{id}', [CashTransferController::class, 'update'])->middleware('permission:cash-accounts.transfers.update');
                    Route::post('/transfers/{id}/submit', [CashTransferController::class, 'submit'])->middleware('permission:cash-accounts.transfers.submit');
                    Route::post('/transfers/{id}/review', [CashTransferController::class, 'review'])->middleware('permission:cash-accounts.transfers.review');
                    Route::post('/transfers/{id}/approve', [CashTransferController::class, 'approve'])->middleware('permission:cash-accounts.transfers.approve');
                    Route::post('/transfers/{id}/post', [CashTransferController::class, 'post'])->middleware('permission:cash-accounts.transfers.post');
                    Route::post('/transfers/{id}/cancel', [CashTransferController::class, 'cancel'])->middleware('permission:cash-accounts.transfers.cancel');
                    Route::post('/transfers/{id}/reverse', [CashTransferController::class, 'reverse'])->middleware('permission:cash-accounts.transfers.reverse');
                    Route::post('/transfers/{id}/evidence', [CashTransferController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.movements.evidence.upload');
                    Route::get('/transfers/{id}/evidence', [CashTransferController::class, 'evidence'])->middleware('permission:cash-accounts.movements.evidence.view');
                    Route::get('/transfers/{id}/evidence/{attachmentId}/download', [CashTransferController::class, 'downloadEvidence'])->middleware('permission:cash-accounts.movements.evidence.download');
                    Route::get('/transfers/{id}/history', [CashTransferController::class, 'history'])->middleware('permission:cash-accounts.movements.history');
                    Route::post('/cash-in/{id}/submit', [CashMovementController::class, 'submit'])->middleware('permission:cash-accounts.cash-in.submit');
                    Route::post('/cash-in/{id}/review', [CashMovementController::class, 'review'])->middleware('permission:cash-accounts.cash-in.review');
                    Route::post('/cash-in/{id}/approve', [CashMovementController::class, 'approve'])->middleware('permission:cash-accounts.cash-in.approve');
                    Route::post('/cash-in/{id}/post', [CashMovementController::class, 'post'])->middleware('permission:cash-accounts.cash-in.post');
                    Route::post('/cash-in/{id}/cancel', [CashMovementController::class, 'cancel'])->middleware('permission:cash-accounts.cash-in.cancel');
                    Route::post('/cash-in/{id}/reverse', [CashMovementController::class, 'reverse'])->middleware('permission:cash-accounts.cash-in.reverse');
                    Route::post('/cash-in/{id}/evidence', [CashMovementController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.movements.evidence.upload');
                    Route::get('/cash-in/{id}/evidence', [CashMovementController::class, 'evidence'])->middleware('permission:cash-accounts.movements.evidence.view');
                    Route::get('/cash-in/{id}/evidence/{attachmentId}/download', [CashMovementController::class, 'downloadEvidence'])->middleware('permission:cash-accounts.movements.evidence.download');
                    Route::get('/cash-in/{id}/history', [CashMovementController::class, 'history'])->middleware('permission:cash-accounts.movements.history');
                    Route::post('/cash-out/{id}/submit', [CashMovementController::class, 'submit'])->middleware('permission:cash-accounts.cash-out.submit');
                    Route::post('/cash-out/{id}/review', [CashMovementController::class, 'review'])->middleware('permission:cash-accounts.cash-out.review');
                    Route::post('/cash-out/{id}/approve', [CashMovementController::class, 'approve'])->middleware('permission:cash-accounts.cash-out.approve');
                    Route::post('/cash-out/{id}/post', [CashMovementController::class, 'post'])->middleware('permission:cash-accounts.cash-out.post');
                    Route::post('/cash-out/{id}/cancel', [CashMovementController::class, 'cancel'])->middleware('permission:cash-accounts.cash-out.cancel');
                    Route::post('/cash-out/{id}/reverse', [CashMovementController::class, 'reverse'])->middleware('permission:cash-accounts.cash-out.reverse');
                    Route::post('/cash-out/{id}/evidence', [CashMovementController::class, 'uploadEvidence'])->middleware('permission:cash-accounts.movements.evidence.upload');
                    Route::get('/cash-out/{id}/evidence', [CashMovementController::class, 'evidence'])->middleware('permission:cash-accounts.movements.evidence.view');
                    Route::get('/cash-out/{id}/evidence/{attachmentId}/download', [CashMovementController::class, 'downloadEvidence'])->middleware('permission:cash-accounts.movements.evidence.download');
                    Route::get('/cash-out/{id}/history', [CashMovementController::class, 'history'])->middleware('permission:cash-accounts.movements.history');
                    Route::get('/{id}', [CashAccountController::class, 'show'])->middleware('permission:cash-accounts.accounts.view');
                    Route::patch('/{id}', [CashAccountController::class, 'update'])->middleware('permission:cash-accounts.accounts.update');
                    Route::post('/{id}/activate', [CashAccountController::class, 'activate'])->middleware('permission:cash-accounts.accounts.activate');
                    Route::post('/{id}/restrict', [CashAccountController::class, 'restrict'])->middleware('permission:cash-accounts.accounts.restrict');
                    Route::post('/{id}/unrestrict', [CashAccountController::class, 'unrestrict'])->middleware('permission:cash-accounts.accounts.activate');
                    Route::post('/{id}/deactivate', [CashAccountController::class, 'deactivate'])->middleware('permission:cash-accounts.accounts.deactivate');
                    Route::post('/{id}/reactivate', [CashAccountController::class, 'reactivate'])->middleware('permission:cash-accounts.accounts.reactivate');
                    Route::get('/{id}/capabilities', [CashAccountController::class, 'show'])->middleware('permission:cash-accounts.accounts.view');
                    Route::patch('/{id}/capabilities', [CashAccountController::class, 'capabilities'])->middleware('permission:cash-accounts.capabilities.manage');
                    Route::get('/{id}/custodians', [CashAccountController::class, 'custodians'])->middleware('permission:cash-accounts.custodians.view');
                    Route::post('/{id}/custodians', [CashAccountController::class, 'assignCustodian'])->middleware('permission:cash-accounts.custodians.manage');
                    Route::post('/{id}/custodians/{custodianId}/end', [CashAccountController::class, 'endCustodian'])->middleware('permission:cash-accounts.custodians.manage');
                    Route::get('/{id}/balance', [CashAccountController::class, 'balance'])->middleware('permission:cash-accounts.balance.view');
                    Route::get('/{id}/movements', [CashAccountController::class, 'movements'])->middleware('permission:cash-accounts.history');
                    Route::get('/{id}/history', [CashAccountController::class, 'history'])->middleware('permission:cash-accounts.history');
                });

                Route::prefix('master-registries')->group(function () {
                    Route::get('/', [MasterRegistryController::class, 'summary'])->middleware('permission:master-registries.view');
                    Route::get('/lookups', [MasterRegistryController::class, 'lookups'])->middleware('permission:master-registries.search');

                    Route::get('/business-partners', [BusinessPartnerController::class, 'index'])->middleware('permission:master-registries.business-partners.view');
                    Route::post('/business-partners', [BusinessPartnerController::class, 'store'])->middleware('permission:master-registries.business-partners.create');
                    Route::post('/business-partners/quick-create', [BusinessPartnerController::class, 'quickCreate'])->middleware('permission:master-registries.business-partners.create');
                    Route::get('/business-partners/{businessPartner}', [BusinessPartnerController::class, 'show'])->middleware('permission:master-registries.business-partners.view');
                    Route::patch('/business-partners/{businessPartner}', [BusinessPartnerController::class, 'update'])->middleware('permission:master-registries.business-partners.update');
                    Route::post('/business-partners/{businessPartner}/deactivate', [BusinessPartnerController::class, 'deactivate'])->middleware('permission:master-registries.business-partners.deactivate');
                    Route::post('/business-partners/{businessPartner}/reactivate', [BusinessPartnerController::class, 'reactivate'])->middleware('permission:master-registries.business-partners.reactivate');
                    Route::get('/business-partners/{businessPartner}/history', [BusinessPartnerController::class, 'history'])->middleware('permission:master-registries.history');
                    Route::post('/business-partners/{businessPartner}/contacts', [BusinessPartnerController::class, 'contact'])->middleware('permission:master-registries.business-partners.update');
                    Route::post('/business-partners/{businessPartner}/addresses', [BusinessPartnerController::class, 'address'])->middleware('permission:master-registries.business-partners.update');

                    Route::get('/products-services', [ProductServiceController::class, 'index'])->middleware('permission:master-registries.items.view');
                    Route::post('/products-services', [ProductServiceController::class, 'store'])->middleware('permission:master-registries.items.create');
                    Route::post('/products-services/quick-create', [ProductServiceController::class, 'quickCreate'])->middleware('permission:master-registries.items.create');
                    Route::get('/products-services/{productService}', [ProductServiceController::class, 'show'])->middleware('permission:master-registries.items.view');
                    Route::patch('/products-services/{productService}', [ProductServiceController::class, 'update'])->middleware('permission:master-registries.items.update');
                    Route::post('/products-services/{productService}/deactivate', [ProductServiceController::class, 'deactivate'])->middleware('permission:master-registries.items.deactivate');
                    Route::post('/products-services/{productService}/reactivate', [ProductServiceController::class, 'reactivate'])->middleware('permission:master-registries.items.reactivate');
                    Route::get('/products-services/{productService}/history', [ProductServiceController::class, 'history'])->middleware('permission:master-registries.history');

                    Route::get('/categories', [CategoryController::class, 'index'])->middleware('permission:master-registries.categories.view');
                    Route::post('/categories', [CategoryController::class, 'store'])->middleware('permission:master-registries.categories.create');
                    Route::get('/categories/{category}', [CategoryController::class, 'show'])->middleware('permission:master-registries.categories.view');
                    Route::patch('/categories/{category}', [CategoryController::class, 'update'])->middleware('permission:master-registries.categories.update');
                    Route::post('/categories/{category}/deactivate', [CategoryController::class, 'deactivate'])->middleware('permission:master-registries.categories.deactivate');
                    Route::post('/categories/{category}/reactivate', [CategoryController::class, 'reactivate'])->middleware('permission:master-registries.categories.reactivate');
                    Route::get('/categories/{category}/history', [CategoryController::class, 'history'])->middleware('permission:master-registries.history');

                    Route::get('/units', [UnitController::class, 'index'])->middleware('permission:master-registries.units.view');
                    Route::post('/units', [UnitController::class, 'store'])->middleware('permission:master-registries.units.create');
                    Route::get('/units/{unit}', [UnitController::class, 'show'])->middleware('permission:master-registries.units.view');
                    Route::patch('/units/{unit}', [UnitController::class, 'update'])->middleware('permission:master-registries.units.update');
                    Route::post('/units/{unit}/deactivate', [UnitController::class, 'deactivate'])->middleware('permission:master-registries.units.deactivate');
                    Route::post('/units/{unit}/reactivate', [UnitController::class, 'reactivate'])->middleware('permission:master-registries.units.reactivate');
                    Route::get('/units/{unit}/history', [UnitController::class, 'history'])->middleware('permission:master-registries.history');

                    Route::get('/reference-lookups', [ReferenceRegistryController::class, 'lookups'])->middleware('permission:master-registries.search');

                    Route::prefix('currencies')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'currencies'])->middleware('permission:master-registries.currencies.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeCurrency'])->middleware('permission:master-registries.currencies.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showCurrency'])->middleware('permission:master-registries.currencies.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateCurrency'])->middleware('permission:master-registries.currencies.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateCurrency'])->middleware('permission:master-registries.currencies.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateCurrency'])->middleware('permission:master-registries.currencies.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyCurrency'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('payment-methods')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'paymentMethods'])->middleware('permission:master-registries.payment-methods.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storePaymentMethod'])->middleware('permission:master-registries.payment-methods.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showPaymentMethod'])->middleware('permission:master-registries.payment-methods.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updatePaymentMethod'])->middleware('permission:master-registries.payment-methods.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivatePaymentMethod'])->middleware('permission:master-registries.payment-methods.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivatePaymentMethod'])->middleware('permission:master-registries.payment-methods.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyPaymentMethod'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('payment-terms')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'paymentTerms'])->middleware('permission:master-registries.payment-terms.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storePaymentTerm'])->middleware('permission:master-registries.payment-terms.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showPaymentTerm'])->middleware('permission:master-registries.payment-terms.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updatePaymentTerm'])->middleware('permission:master-registries.payment-terms.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivatePaymentTerm'])->middleware('permission:master-registries.payment-terms.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivatePaymentTerm'])->middleware('permission:master-registries.payment-terms.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyPaymentTerm'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('tax-codes')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'taxCodes'])->middleware('permission:master-registries.tax-codes.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeTaxCode'])->middleware('permission:master-registries.tax-codes.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showTaxCode'])->middleware('permission:master-registries.tax-codes.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateTaxCode'])->middleware('permission:master-registries.tax-codes.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateTaxCode'])->middleware('permission:master-registries.tax-codes.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateTaxCode'])->middleware('permission:master-registries.tax-codes.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyTaxCode'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('account-titles')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'accountTitles'])->middleware('permission:master-registries.account-titles.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeAccountTitle'])->middleware('permission:master-registries.account-titles.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showAccountTitle'])->middleware('permission:master-registries.account-titles.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateAccountTitle'])->middleware('permission:master-registries.account-titles.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateAccountTitle'])->middleware('permission:master-registries.account-titles.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateAccountTitle'])->middleware('permission:master-registries.account-titles.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyAccountTitle'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('expense-categories')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'expenseCategories'])->middleware('permission:master-registries.expense-categories.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeExpenseCategory'])->middleware('permission:master-registries.expense-categories.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showExpenseCategory'])->middleware('permission:master-registries.expense-categories.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateExpenseCategory'])->middleware('permission:master-registries.expense-categories.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateExpenseCategory'])->middleware('permission:master-registries.expense-categories.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateExpenseCategory'])->middleware('permission:master-registries.expense-categories.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyExpenseCategory'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('branches')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'branches'])->middleware('permission:master-registries.branches.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeBranch'])->middleware('permission:master-registries.branches.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showBranch'])->middleware('permission:master-registries.branches.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateBranch'])->middleware('permission:master-registries.branches.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateBranch'])->middleware('permission:master-registries.branches.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateBranch'])->middleware('permission:master-registries.branches.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyBranch'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('warehouses')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'warehouses'])->middleware('permission:master-registries.warehouses.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeWarehouse'])->middleware('permission:master-registries.warehouses.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showWarehouse'])->middleware('permission:master-registries.warehouses.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateWarehouse'])->middleware('permission:master-registries.warehouses.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateWarehouse'])->middleware('permission:master-registries.warehouses.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateWarehouse'])->middleware('permission:master-registries.warehouses.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyWarehouse'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('stock-locations')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'stockLocations'])->middleware('permission:master-registries.stock-locations.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeStockLocation'])->middleware('permission:master-registries.stock-locations.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showStockLocation'])->middleware('permission:master-registries.stock-locations.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateStockLocation'])->middleware('permission:master-registries.stock-locations.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateStockLocation'])->middleware('permission:master-registries.stock-locations.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateStockLocation'])->middleware('permission:master-registries.stock-locations.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyStockLocation'])->middleware('permission:master-registries.history');
                    });
                    Route::prefix('reason-codes')->group(function () {
                        Route::get('/', [ReferenceRegistryController::class, 'reasonCodes'])->middleware('permission:master-registries.reason-codes.view');
                        Route::post('/', [ReferenceRegistryController::class, 'storeReasonCode'])->middleware('permission:master-registries.reason-codes.create');
                        Route::get('/{id}', [ReferenceRegistryController::class, 'showReasonCode'])->middleware('permission:master-registries.reason-codes.view');
                        Route::patch('/{id}', [ReferenceRegistryController::class, 'updateReasonCode'])->middleware('permission:master-registries.reason-codes.update');
                        Route::post('/{id}/deactivate', [ReferenceRegistryController::class, 'deactivateReasonCode'])->middleware('permission:master-registries.reason-codes.deactivate');
                        Route::post('/{id}/reactivate', [ReferenceRegistryController::class, 'reactivateReasonCode'])->middleware('permission:master-registries.reason-codes.reactivate');
                        Route::get('/{id}/history', [ReferenceRegistryController::class, 'historyReasonCode'])->middleware('permission:master-registries.history');
                    });
                });
            });
        });
    });
});
