<?php

namespace App\Http\Resources\CashAccounts;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CashMovementDocumentResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return ['id' => $this->id, 'company_id' => $this->company_id, 'document_number' => $this->document_number, 'purpose' => $this->whenLoaded('purpose', fn () => ['code' => $this->purpose?->code, 'name' => $this->purpose?->name, 'document_kind' => $this->purpose?->document_kind]), 'source_type' => $this->source_type, 'source_record_type' => $this->source_record_type, 'source_record_id' => $this->source_record_id, 'external_reference' => $this->external_reference, 'cash_account_id' => $this->cash_account_id, 'cash_account' => $this->whenLoaded('account', fn () => $this->account ? ['id' => $this->account->id, 'code' => $this->account->code, 'name' => $this->account->name, 'masked_account_identifier' => $this->account->masked_account_identifier] : null), 'currency' => $this->whenLoaded('currency', fn () => $this->currency ? ['id' => $this->currency->id, 'code' => $this->currency->code, 'name' => $this->currency->name] : null), 'direction' => $this->direction, 'amount' => (string) $this->amount, 'business_date' => $this->business_date?->toDateString(), 'posted_at' => $this->posted_at, 'payment_method' => $this->whenLoaded('paymentMethod', fn () => $this->paymentMethod ? ['id' => $this->paymentMethod->id, 'code' => $this->paymentMethod->code, 'name' => $this->paymentMethod->name] : null), 'reason_code' => $this->whenLoaded('reasonCode', fn () => $this->reasonCode ? ['id' => $this->reasonCode->id, 'code' => $this->reasonCode->code, 'name' => $this->reasonCode->name, 'domain' => $this->reasonCode->domain] : null), 'explanation' => $this->explanation, 'supporting_reference' => $this->supporting_reference, 'status' => $this->status, 'version' => $this->version, 'submitted_version' => $this->submitted_version, 'prepared_by' => $this->prepared_by, 'submitted_by' => $this->submitted_by, 'reviewed_by' => $this->reviewed_by, 'approved_by' => $this->approved_by, 'posted_by' => $this->posted_by, 'cancelled_by' => $this->cancelled_by, 'reversed_by' => $this->reversed_by, 'return_reason' => $this->return_reason, 'cancellation_reason' => $this->cancellation_reason, 'reversal_reason' => $this->reversal_reason, 'negative_balance_override' => $this->negative_balance_override, 'cash_movement_id' => $this->cash_movement_id, 'accounting_transaction_id' => $this->accounting_transaction_id, 'original_document_id' => $this->original_document_id, 'reversal_document_id' => $this->reversal_document_id, 'attachments' => $this->whenLoaded('attachments', fn () => $this->attachments->map(fn ($attachment) => ['id' => $attachment->id, 'original_filename' => $attachment->original_filename, 'mime_type' => $attachment->mime_type, 'file_size' => $attachment->file_size, 'file_hash' => $attachment->file_hash, 'uploaded_at' => $attachment->created_at])->values()), 'movement' => $this->whenLoaded('movement', fn () => $this->movement ? new CashMovementResource($this->movement) : null)];
    }
}
