<?php

namespace App\Http\Resources\CashAccounts;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CashTransferResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return ['id' => $this->id, 'company_id' => $this->company_id, 'document_number' => $this->document_number, 'purpose' => $this->purpose, 'source_cash_account_id' => $this->source_cash_account_id, 'source_cash_account' => $this->whenLoaded('sourceAccount', fn () => $this->sourceAccount ? ['id' => $this->sourceAccount->id, 'code' => $this->sourceAccount->code, 'name' => $this->sourceAccount->name, 'currency' => $this->sourceAccount->currency?->code] : null), 'destination_cash_account_id' => $this->destination_cash_account_id, 'destination_cash_account' => $this->whenLoaded('destinationAccount', fn () => $this->destinationAccount ? ['id' => $this->destinationAccount->id, 'code' => $this->destinationAccount->code, 'name' => $this->destinationAccount->name, 'currency' => $this->destinationAccount->currency?->code] : null), 'currency' => $this->whenLoaded('currency', fn () => $this->currency ? ['id' => $this->currency->id, 'code' => $this->currency->code, 'name' => $this->currency->name] : null), 'amount' => (string) $this->amount, 'business_date' => $this->business_date?->toDateString(), 'expected_completion_date' => $this->expected_completion_date?->toDateString(), 'external_reference' => $this->external_reference, 'explanation' => $this->explanation, 'reason_code' => $this->whenLoaded('reasonCode', fn () => $this->reasonCode ? ['id' => $this->reasonCode->id, 'code' => $this->reasonCode->code, 'name' => $this->reasonCode->name, 'domain' => $this->reasonCode->domain] : null), 'status' => $this->status, 'version' => $this->version, 'submitted_version' => $this->submitted_version, 'prepared_by' => $this->prepared_by, 'submitted_by' => $this->submitted_by, 'reviewed_by' => $this->reviewed_by, 'approved_by' => $this->approved_by, 'posted_by' => $this->posted_by, 'cancelled_by' => $this->cancelled_by, 'reversed_by' => $this->reversed_by, 'return_reason' => $this->return_reason, 'cancellation_reason' => $this->cancellation_reason, 'reversal_reason' => $this->reversal_reason, 'source_movement_id' => $this->source_movement_id, 'destination_movement_id' => $this->destination_movement_id, 'accounting_transaction_id' => $this->accounting_transaction_id, 'original_document_id' => $this->original_document_id, 'reversal_document_id' => $this->reversal_document_id, 'legs' => $this->whenLoaded('legs', fn () => $this->legs->map(fn ($leg) => ['id' => $leg->id, 'cash_movement_id' => $leg->cash_movement_id, 'cash_account_id' => $leg->cash_account_id, 'direction' => $leg->direction, 'movement' => $leg->movement ? new CashMovementResource($leg->movement) : null])->values()), 'attachments' => $this->whenLoaded('attachments', fn () => $this->attachments->map(fn ($attachment) => ['id' => $attachment->id, 'original_filename' => $attachment->original_filename, 'mime_type' => $attachment->mime_type, 'file_size' => $attachment->file_size, 'file_hash' => $attachment->file_hash])->values())];
    }
}
