<?php

namespace App\Http\Resources\CashAccounts;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CashCountResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return ['id' => $this->id, 'company_id' => $this->company_id, 'count_number' => $this->count_number, 'cash_account_id' => $this->cash_account_id, 'cash_account' => $this->whenLoaded('account', fn () => ['id' => $this->account->id, 'code' => $this->account->code, 'name' => $this->account->name, 'status' => $this->account->status, 'currency' => $this->account->currency?->code]), 'count_type' => $this->whenLoaded('type', fn () => ['code' => $this->type->code, 'name' => $this->type->name, 'rules' => $this->type->rules]), 'currency' => $this->whenLoaded('currency', fn () => ['id' => $this->currency->id, 'code' => $this->currency->code, 'name' => $this->currency->name]), 'branch' => $this->whenLoaded('branch', fn () => $this->branch ? ['id' => $this->branch->id, 'code' => $this->branch->code, 'name' => $this->branch->name] : null), 'status' => $this->status, 'count_date' => $this->count_date?->toDateString(), 'cut_off_at' => $this->cut_off_at, 'expected_as_of_at' => $this->expected_as_of_at, 'count_started_at' => $this->count_started_at, 'expected_amount' => $this->expected_amount === null ? null : (string) $this->expected_amount, 'expected_snapshot_generated_at' => $this->expected_snapshot_generated_at, 'expected_snapshot_hash' => $this->expected_snapshot_hash, 'expected_movement_count' => $this->expected_movement_count, 'post_cutoff_movement_count' => $this->post_cutoff_movement_count, 'post_cutoff_movement_ids' => $this->post_cutoff_movement_ids, 'actual_amount' => $this->actual_amount === null ? null : (string) $this->actual_amount, 'variance_amount' => $this->variance_amount === null ? null : (string) $this->variance_amount, 'variance_classification' => $this->variance_classification, 'recount_required' => $this->recount_required, 'recount_count' => $this->recount_count, 'current_custodian_id' => $this->current_custodian_id, 'counter_id' => $this->counter_id, 'witness_id' => $this->witness_id, 'incoming_custodian_id' => $this->incoming_custodian_id, 'outgoing_custodian_id' => $this->outgoing_custodian_id, 'reviewer_id' => $this->reviewer_id, 'approver_id' => $this->approver_id, 'version' => $this->version, 'current_attempt' => $this->whenLoaded('currentAttempt', fn () => new CashCountAttemptResource($this->currentAttempt)), 'attempts' => $this->whenLoaded('attempts', fn () => CashCountAttemptResource::collection($this->attempts)), 'variance' => $this->whenLoaded('variance', fn () => $this->variance ? new CashCountVarianceResource($this->variance) : null), 'adjustment' => $this->whenLoaded('adjustment', fn () => $this->adjustment ? new CashAdjustmentResource($this->adjustment) : null), 'attachments' => $this->whenLoaded('attachments', fn () => $this->attachments->map(fn ($item) => ['id' => $item->id, 'original_filename' => $item->original_filename, 'mime_type' => $item->mime_type, 'file_size' => $item->file_size])->values())];
    }
}
