<?php

namespace App\Http\Resources\CashAccounts;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CashAccountResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return ['id' => $this->id, 'company_id' => $this->company_id, 'code' => $this->code, 'name' => $this->name, 'display_name' => $this->display_name, 'status' => $this->status, 'version' => $this->version, 'cash_account_type' => new CashAccountTypeResource($this->whenLoaded('type')), 'account_title' => $this->whenLoaded('accountTitle', fn () => $this->accountTitle ? ['id' => $this->accountTitle->id, 'code' => $this->accountTitle->code, 'name' => $this->accountTitle->name, 'classification' => $this->accountTitle->classification] : null), 'currency' => $this->whenLoaded('currency', fn () => $this->currency ? ['id' => $this->currency->id, 'code' => $this->currency->code, 'name' => $this->currency->name, 'symbol' => $this->currency->symbol, 'decimal_precision' => $this->currency->decimal_precision] : null), 'branch' => $this->whenLoaded('branch', fn () => $this->branch ? ['id' => $this->branch->id, 'code' => $this->branch->code, 'name' => $this->branch->name] : null), 'institution' => $this->whenLoaded('institution', fn () => $this->institution ? ['id' => $this->institution->id, 'provider_type' => $this->institution->provider_type, 'name' => $this->institution->name, 'branch_name' => $this->institution->branch_name, 'routing_reference' => $this->institution->routing_reference, 'statement_format' => $this->institution->statement_format] : null), 'masked_account_identifier' => $this->masked_account_identifier, 'account_identifier_last4' => $this->account_identifier_last4, 'external_reference' => $this->external_reference, 'account_subtype' => $this->account_subtype, 'notes' => $this->notes, 'restricted_capabilities' => $this->restricted_capabilities, 'capabilities' => $this->whenLoaded('capabilities', fn () => $this->capabilities->map(fn ($capability) => ['code' => $capability->capability, 'enabled' => $capability->enabled, 'version' => $capability->version])->values()), 'custodians' => $this->whenLoaded('custodians', fn () => $this->custodians->map(fn ($assignment) => ['id' => $assignment->id, 'user_id' => $assignment->user_id, 'user_name' => $assignment->user?->name, 'user_email' => $assignment->user?->email, 'responsibility_type' => $assignment->responsibility_type, 'effective_from' => $assignment->effective_from?->toDateString(), 'effective_to' => $assignment->effective_to?->toDateString(), 'is_primary' => $assignment->is_primary, 'status' => $assignment->status, 'version' => $assignment->version])->values()), 'position' => $this->position ?? null, 'last_activity_at' => $this->last_activity_at, 'last_count_at' => $this->last_count_at, 'last_reconciliation_at' => $this->last_reconciliation_at, 'status_reason' => $this->status_reason, 'activated_at' => $this->activated_at, 'restricted_at' => $this->restricted_at, 'deactivated_at' => $this->deactivated_at, 'reactivated_at' => $this->reactivated_at, 'created_at' => $this->created_at, 'updated_at' => $this->updated_at];
    }
}
