import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, Banknote, CheckCircle2, CreditCard, LoaderCircle } from 'lucide-react'
import { apiFetch, newIdempotencyKey } from '../../lib/api'

type Envelope<T> = { data: T }
type Sale = { id: string; sale_number: string; total: string; remaining_amount: string; currency_id?: string; currency?: { code?: string; symbol?: string }; customer?: { display_name?: string } | null; version: number }
type PaymentMethod = { id: string; name: string; code: string }
type CashAccount = { id: string; name?: string; display_name?: string; currency_id: string; currency?: { code?: string } }
type Lookups = { payment_methods: PaymentMethod[]; cash_accounts: CashAccount[] }

export function SalesPaidNowPanel() {
  const client = useQueryClient()
  const [openId, setOpenId] = useState<string | null>(null)
  const [amount, setAmount] = useState('')
  const [methodId, setMethodId] = useState('')
  const [accountId, setAccountId] = useState('')
  const [message, setMessage] = useState('')
  const sales = useQuery({ queryKey: ['simplebiz', 'sales', 'cash-approved'], queryFn: () => apiFetch<Envelope<Sale[]>>('/sales?payment_basis=cash&status=approved&per_page=50') })
  const lookups = useQuery({ queryKey: ['simplebiz', 'collections', 'lookups'], queryFn: () => apiFetch<Envelope<Lookups>>('/collections/lookups') })
  const complete = useMutation({ mutationFn: (sale: Sale) => apiFetch<Envelope<{ sale: Sale; receipt: { receipt_number: string } }>>(`/sales/${sale.id}/paid-now`, { method: 'POST', headers: { 'Idempotency-Key': newIdempotencyKey() }, body: JSON.stringify({ receipt_date: new Date().toISOString().slice(0, 10), amount, payment_method_id: methodId, cash_account_id: accountId }) }), onSuccess: (response) => { setMessage(`Sale completed and receipt ${response.data.receipt.receipt_number} was posted.`); setOpenId(null); void client.invalidateQueries({ queryKey: ['simplebiz', 'sales'] }); void client.invalidateQueries({ queryKey: ['simplebiz', 'sales', 'cash-approved'] }) } })
  const begin = (sale: Sale) => { setOpenId(sale.id); setAmount(sale.remaining_amount || sale.total); setMethodId(lookups.data?.data.payment_methods[0]?.id ?? ''); setAccountId(lookups.data?.data.cash_accounts.find((account) => account.currency_id === sale.currency_id)?.id ?? lookups.data?.data.cash_accounts[0]?.id ?? ''); setMessage('') }
  const accounts = lookups.data?.data.cash_accounts ?? []
  return <section id="paid-now" className="sb-sales-completion-card"><header><span><Banknote aria-hidden="true" />Paid-now cash sales</span><small>{sales.data?.data.length ?? 0} approved</small></header><p className="sb-sales-completion-intro">Complete an approved cash Sale in one controlled journey. The linked receipt, receivable application, inventory effect, cash movement, and accounting effects are posted through their owning modules.</p>{message && <p className="sb-sales-completion-toast"><CheckCircle2 size={15} />{message}</p>}{sales.isPending ? <p className="sb-sales-completion-empty"><LoaderCircle className="sb-sales-spin" size={14} /> Loading approved cash Sales…</p> : sales.isError ? <p className="sb-sales-completion-error">Unable to load approved cash Sales.</p> : sales.data?.data.length ? <div className="sb-sales-completion-queue">{sales.data.data.map((sale) => <div key={sale.id} className="sb-sales-completion-row"><span><strong>{sale.sale_number}</strong><small>{sale.customer?.display_name ?? 'Customer'} · {sale.currency?.symbol ?? sale.currency?.code ?? ''} {Number(sale.remaining_amount || sale.total).toLocaleString()}</small></span>{openId === sale.id ? <div className="grid w-full gap-2 sm:grid-cols-[130px_1fr_1fr_auto]"><input aria-label={`Payment amount for ${sale.sale_number}`} type="number" min="0.01" max={sale.remaining_amount || sale.total} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /><select aria-label={`Payment method for ${sale.sale_number}`} value={methodId} onChange={(event) => setMethodId(event.target.value)}><option value="">Payment method</option>{lookups.data?.data.payment_methods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</select><select aria-label={`Cash account for ${sale.sale_number}`} value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Cash account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.display_name ?? account.name}</option>)}</select><button type="button" disabled={complete.isPending || !methodId || !accountId || !amount} onClick={() => complete.mutate(sale)}>{complete.isPending ? 'Posting…' : 'Complete'}</button></div> : <button type="button" onClick={() => begin(sale)}><CreditCard size={14} /> Record payment <ArrowRight size={13} /></button>}</div>)}</div> : <p className="sb-sales-completion-empty">No approved cash Sales are waiting for payment. Create or approve a cash Sale first; this queue never creates a second receipt for an already completed Sale.</p>}{complete.error && <p className="sb-sales-completion-error">{complete.error instanceof Error ? complete.error.message : 'Unable to complete the paid-now Sale.'}</p>}</section>
}
