import { useEffect, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../../lib/api'
import { Badge, Card, EmptyState, ErrorPanel, LoadingPanel, PageHeader } from '../../components/ui'

type DashboardSummary = { account_count: number; active_account_count: number; restricted_account_count: number; draft_account_count: number; position_by_currency: { currency_code: string; posted_balance: string }[]; as_of: string }
type DashboardAttention = { draft_accounts?: unknown[]; opening_balances_pending?: unknown[]; configuration?: { ready_for_posting?: boolean } }
type DashboardAction = { icon: string; title: string; description: string; action: string; tone: string; to?: string }

const actions: DashboardAction[] = [
  { icon: '▣', title: 'Sales', description: 'Sales & Receivables is not yet implemented.', action: 'Deferred', tone: 'sb-tone-yellow' },
  { icon: '◈', title: 'Collections', description: 'Collections & Receipts is not yet implemented.', action: 'Deferred', tone: 'sb-tone-mint' },
  { icon: '▰', title: 'Purchases', description: 'Purchases & Payables is not yet implemented.', action: 'Deferred', tone: 'sb-tone-peach' },
  { icon: '▤', title: 'Payments', description: 'Payments & Disbursements is not yet implemented.', action: 'Deferred', tone: 'sb-tone-lilac' },
  { icon: '▦', title: 'Inventory', description: 'Inventory transactions are not yet implemented.', action: 'Deferred', tone: 'sb-tone-sand' },
  { icon: '▣', title: 'Cash Accounts', description: 'Review governed cash accounts and posted positions.', action: 'Open workspace', tone: 'sb-tone-mint', to: '/cash-accounts' },
  { icon: '▰', title: 'Expenses', description: 'Expenses is not yet implemented.', action: 'Deferred', tone: 'sb-tone-rose' },
]

export function DashboardPage() {
  const [summary, setSummary] = useState<DashboardSummary | null>(null)
  const [attention, setAttention] = useState<DashboardAttention | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = () => { setLoading(true); setError(''); Promise.all([apiFetch<{ data: DashboardSummary }>('/cash-accounts/summary'), apiFetch<{ data: DashboardAttention }>('/cash-accounts/needs-attention')]).then(([summaryResponse, attentionResponse]) => { setSummary(summaryResponse.data); setAttention(attentionResponse.data) }).catch((caught) => setError(caught instanceof Error ? caught.message : 'Cash position data is unavailable.')).finally(() => setLoading(false)) }
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [])
  const asOf = summary?.as_of ? `Cash position as of ${new Date(summary.as_of).toLocaleString()}` : 'Current company scope · live data appears when Cash Accounts are configured'
  return <><PageHeader icon="▦" title="Dashboard" subtitle="Monitor your business, manage daily activities, and act on what needs attention." context={asOf} /><div className="sb-action-grid">{actions.map((action) => <ActionCard key={action.title} action={action} />)}</div><div className="sb-dashboard-grid sb-dashboard-grid-primary"><Panel title="Needs Attention" action={attention && <Badge tone="warning">{(attention.draft_accounts?.length ?? 0) + (attention.opening_balances_pending?.length ?? 0)} items</Badge>}>{loading ? <LoadingPanel label="Loading attention data…" /> : error ? <ErrorPanel message={error} onRetry={load} /> : <Attention attention={attention} />}</Panel><Panel title="Profit & Loss Snapshot"><EmptyState title="Not available yet" detail="Profit and loss is owned by the future Sales, Purchases, and Expenses modules. No placeholder values are shown." /></Panel><Panel title="Business Snapshot"><CashPosition summary={summary} loading={loading} /></Panel></div><div className="sb-dashboard-grid sb-dashboard-grid-secondary"><Panel title="Recent Activity"><EmptyState title="No dashboard activity feed yet" detail="Recent activity will appear when an owning activity projection is available." /></Panel><Panel title="Records & Ledgers"><div className="sb-link-grid">{['Sales History', 'Collection History', 'Purchase History', 'Cash Account History', 'Customer Ledger', 'Payment History'].map((item) => <div key={item} className="sb-deferred-link"><span aria-hidden="true">▣</span><span>{item}</span><Badge>Deferred</Badge></div>)}</div></Panel><Panel title="Action Center"><div className="sb-action-list"><Link to="/cash-accounts?mode=movement&kind=cash_in" className="sb-quick-action">▤ <span>Record cash in</span></Link><Link to="/cash-accounts?mode=movement&kind=cash_out" className="sb-quick-action">▤ <span>Record cash out</span></Link><Link to="/cash-accounts?mode=counts" className="sb-quick-action">▦ <span>Cash counts</span></Link><Link to="/cash-accounts?mode=reconciliations" className="sb-quick-action">▤ <span>Reconciliations</span></Link></div></Panel></div></>
}

function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <Card><div className="sb-panel-heading"><h2><span aria-hidden="true">☷</span>{title}</h2>{action}</div>{children}</Card> }
function ActionCard({ action }: { action: DashboardAction }) { const body = <><div className="sb-action-icon" aria-hidden="true">{action.icon}</div><h2>{action.title}</h2><p>{action.description}</p><span className={`sb-card-action ${action.to ? '' : 'sb-card-action-deferred'}`}>{action.action}{action.to && <span aria-hidden="true"> →</span>}</span></>; return action.to ? <Link to={action.to} className={`sb-action-card ${action.tone}`}>{body}</Link> : <article className={`sb-action-card ${action.tone} sb-action-card-deferred`} aria-label={`${action.title}, deferred`}>{body}</article> }
function Attention({ attention }: { attention: DashboardAttention | null }) { const draftCount = attention?.draft_accounts?.length ?? 0; const openingCount = attention?.opening_balances_pending?.length ?? 0; const configurationReady = attention?.configuration?.ready_for_posting; if (!draftCount && !openingCount && configurationReady !== false) return <EmptyState title="Nothing needs attention" detail="The Cash Accounts attention feed has no outstanding items for this company." />; return <div className="sb-attention-list">{draftCount > 0 && <div><Badge tone="warning">{draftCount}</Badge><span><strong>Draft Cash Account profiles</strong><small>Complete identity and control metadata before activation.</small></span></div>}{openingCount > 0 && <div><Badge tone="info">{openingCount}</Badge><span><strong>Opening balances pending</strong><small>Review evidence and governed posting status.</small></span></div>}{configurationReady === false && <div><Badge tone="danger">!</Badge><span><strong>Posting configuration required</strong><small>Cash postings remain blocked until configuration is ready.</small></span></div>}</div> }
function CashPosition({ summary, loading }: { summary: DashboardSummary | null; loading: boolean }) { if (loading) return <LoadingPanel label="Loading cash position…" />; if (!summary?.position_by_currency?.length) return <EmptyState title="No posted cash position yet" detail="Cash balances will appear by currency after the backend has posted Cash Account movements." />; return <div><div className="sb-currency-list">{summary.position_by_currency.map((item) => <div key={item.currency_code}><span>{item.currency_code}</span><strong>{item.posted_balance}</strong></div>)}</div><p className="sb-panel-note">Derived from posted movements. No balance is calculated or edited in the frontend.</p></div> }
