worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 25m;

    server {
        listen ${PORT};
        listen [::]:${PORT};
        server_name _;
        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS $http_x_forwarded_proto;
            fastcgi_pass 127.0.0.1:9000;
        }

        location ~ /\. {
            deny all;
        }
    }
}
